name: crazyforlife
favicon: null
layout_spectrum: 0.29241991229355335
typography_spectrum: 0.6553533629048616
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.28717528213746846
  lightness: 0.6476436189841479
  saturation: 0.20085067814216018
  rhythmicContrast: 0.06012997287325561
purpose: []
