name: crazyforlife
favicon: null
layout_spectrum: 0.75241
typography_spectrum: 0.6553533629048616
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f05b30'
    - '#f9b049'
    - '#ffffff'
    - '#c76749'
    - '#fa9b46'
  brandStrength: 0.28717528213746846
  lightness: 0.6476436189841479
  saturation: 0.20085067814216018
  rhythmicContrast: 0.06012997287325561
purpose: []
